// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH-3PYZI9QL8TsojvBqg4MACQjE4W1DlQ',
    appId: '1:334136564931:web:59b55f4dc2de9b32b15676',
    messagingSenderId: '334136564931',
    projectId: 'flutterecommerce-fc124',
    authDomain: 'flutterecommerce-fc124.firebaseapp.com',
    storageBucket: 'flutterecommerce-fc124.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH-3PYZI9QL8TsojvBqg4MACQjE4W1DlQ',
    appId: '1:334136564931:android:59b55f4dc2de9b32b15676',
    messagingSenderId: '334136564931',
    projectId: 'flutterecommerce-fc124',
    storageBucket: 'flutterecommerce-fc124.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH-3PYZI9QL8TsojvBqg4MACQjE4W1DlQ',
    appId: '1:334136564931:ios:59b55f4dc2de9b32b15676',
    messagingSenderId: '334136564931',
    projectId: 'flutterecommerce-fc124',
    storageBucket: 'flutterecommerce-fc124.firebasestorage.app',
    iosClientId: '334136564931-ios.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH-3PYZI9QL8TsojvBqg4MACQjE4W1DlQ',
    appId: '1:334136564931:ios:59b55f4dc2de9b32b15676',
    messagingSenderId: '334136564931',
    projectId: 'flutterecommerce-fc124',
    storageBucket: 'flutterecommerce-fc124.firebasestorage.app',
    iosClientId: '334136564931-ios.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerce',
  );
}
