// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_ecommerce/test/repositories/favorite_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_ecommerce/entities/favorite.dart' as _i4;
import 'package:flutter_ecommerce/repositories/favorite_repository_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FavoriteRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteRepositoryInterface extends _i1.Mock
    implements _i2.FavoriteRepositoryInterface {
  MockFavoriteRepositoryInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> addToFavorites(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [productId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> removeFromFavorites(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [productId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> isFavorite(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [productId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Favorite?> getFavoriteByProductId(int? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteByProductId,
          [productId],
        ),
        returnValue: _i3.Future<_i4.Favorite?>.value(),
      ) as _i3.Future<_i4.Favorite?>);

  @override
  _i3.Future<List<_i4.Favorite>> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Favorite>>.value(<_i4.Favorite>[]),
      ) as _i3.Future<List<_i4.Favorite>>);

  @override
  _i3.Future<int> clearFavorites() => (super.noSuchMethod(
        Invocation.method(
          #clearFavorites,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getFavoriteCount() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> toggleFavorite(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [productId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
