name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Format code
        run: dart format .
      - name: Analyze
        run: flutter analyze

      # - name: Test with coverage
      #   run: flutter test --coverage test/entities/ || true

      # - name: Enforce 50% min coverage
      #   run: |
      #     if [ -f coverage/lcov.info ]; then
      #       total_lf=$(grep -E "^LF:" coverage/lcov.info | awk -F: '{s+=$2} END{print s}')
      #       total_lh=$(grep -E "^LH:" coverage/lcov.info | awk -F: '{s+=$2} END{print s}')
      #       pct=$(python3 - <<'PY'
      #     total_lf = int("${total_lf}")
      #     total_lh = int("${total_lh}")
      #     print(f"{(total_lh/total_lf)*100:.2f}")
      #     PY
      #     )
      #       echo "Coverage: ${pct}% (${total_lh}/${total_lf})"
      #       # Temporairement désactivé - awk "BEGIN { exit (${pct} >= 50.0 ? 0 : 1) }"
      #       echo "Coverage check temporarily disabled"
      #     else
      #       echo "No coverage file found, skipping coverage check"
      #     fi

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: lcov.info
          path: coverage/lcov.info
